queue_order.settings:
  type: config_object
  label: 'Queue Order config'
  mapping:
    order:
      type: sequence
      label: 'Queue order'
      sequence:
        - type: queue_order.settings.order.[%key]
queue_order.settings.order.*:
  type: integer
  label: 'Weight for % queue'
